version: 1
default_environment: dev
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-bigquery
    variant: matatika
    pip_url: git+https://github.com/Matatika/tap-bigquery@v0.3.0
    config:
      stream_maps:
        analytics_*-events_*:
          __alias__: events
          __key_properties__:
          - event_timestamp
          - event_name
          - event_bundle_sequence_id
  loaders:
  - name: target-postgres
    variant: matatika
    pip_url: git+https://github.com/Matatika/pipelinewise-target-postgres@v0.2.0
    annotations:
      matatika:
        properties_from_datastore: Warehouse
  - name: target-snowflake
    variant: meltanolabs
    pip_url: meltanolabs-target-snowflake
jobs:
- name: BigQuery GA4 export
  tasks:
  - - tap-bigquery
    - target-postgres
- name: BigQuery GA4 export to Snowflake
  tasks:
  - - tap-bigquery
    - target-snowflake